export const emloyeeData = [
  {
    id: "1",

    employeeName: "Sara ahmed khaled",
    position: "",
    department: "",
    // empCase: "absent",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "2",

    employeeName: "amir ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "weekend",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "3",

    employeeName: "soha ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "on leave",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "4",

    employeeName: "noha ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "present",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "5",

    employeeName: "magi ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "absent",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "6",

    employeeName: "roby ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "weekend",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "7",

    employeeName: "alex ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "on leave",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "8",

    employeeName: "lolo ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "on leave",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "9",

    employeeName: "lili ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "on leave",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "10",

    employeeName: "samir ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "present",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "11",
    employeeName: "noha ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "on leave",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
  {
    id: "12",
    employeeName: "Sara ahmed khaled",
    position: "hr department",
    department: "business",
    empCase: "present",
    role: "Employee",
    manger: "Mohamed Tarek",
    office: "Arabic Localizer",
    date: "12/12/2022",
  },
];
